In [58]:
import pandas as pd
import numpy as np

In [59]:
pd.set_option("display.max_columns",None) #display todas las columnas

In [60]:
df_talento = pd.read_csv("hr.csv")

In [61]:
df_talento.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,sALES eXECUTIVE,4.0,Single,5993.0,19479,8,Y,Yes,11,3,1,80.0,0,8,0.0,1,6,4,0,5.0
1,49.0,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,rESEARCH sCIENTIST,2.0,Married,5130.0,24907,1,Y,No,23,4,4,NaN,1,10,3.0,3,10,7,1,7.0
2,37.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,lABORATORY tECHNICIAN,3.0,Single,2090.0,2396,6,Y,Yes,15,3,2,NaN,0,7,3.0,3,0,0,0,0.0
3,33.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,rESEARCH sCIENTIST,3.0,Married,2909.0,23159,1,Y,Yes,11,3,3,80.0,0,8,3.0,3,8,7,3,0.0
4,27.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,lABORATORY tECHNICIAN,2.0,Married,3468.0,16632,9,Y,No,12,3,4,80.0,1,6,3.0,3,2,2,2,2.0
5,32.0,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,4,Male,79,3,1,lABORATORY tECHNICIAN,4.0,Single,3068.0,11864,0,Y,No,13,3,3,80.0,0,8,2.0,2,7,7,3,6.0
6,59.0,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,3,Female,81,4,1,lABORATORY tECHNICIAN,1.0,Married,2670.0,9964,4,Y,NaN,20,4,1,NaN,3,12,3.0,2,1,0,0,NaN
7,30.0,No,Travel_Rarely,1358,NaN,24,1,Life Sciences,1,11,4,Male,67,3,1,lABORATORY tECHNICIAN,3.0,Divorced,2693.0,13335,1,Y,No,22,4,2,80.0,1,1,2.0,3,1,0,0,0.0
8,38.0,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,4,Male,44,2,3,mANUFACTURING dIRECTOR,3.0,Single,9526.0,8787,0,Y,No,21,4,2,80.0,0,10,2.0,3,9,7,1,8.0
9,36.0,No,Travel_Rarely,1299,Research & Development,27,3,NaN,1,13,3,Male,94,3,2,hEALTHCARE rEPRESENTATIVE,3.0,Married,5237.0,16577,6,Y,No,13,3,2,80.0,2,17,3.0,2,7,7,7,NaN

In [62]:
df_talento.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [63]:
pd.Series(df_talento.columns)

0                          Age
1                    Attrition
2               BusinessTravel
3                    DailyRate
4                   Department
5             DistanceFromHome
6                    Education
7               EducationField
8                EmployeeCount
9               EmployeeNumber
10     EnvironmentSatisfaction
11                      Gender
12                  HourlyRate
13              JobInvolvement
14                    JobLevel
15                     JobRole
16             JobSatisfaction
17               MaritalStatus
18               MonthlyIncome
19                 MonthlyRate
20          NumCompaniesWorked
21                      Over18
22                    OverTime
23           PercentSalaryHike
24           PerformanceRating
25    RelationshipSatisfaction
26               StandardHours
27            StockOptionLevel
28           TotalWorkingYears
29       TrainingTimesLastYear
30             WorkLifeBalance
31              YearsAtCompany
32          YearsInCurrentRole
33     YearsSinceLastPromotion
34        YearsWithCurrManager
dtype: str

In [64]:
df_talento.shape #aqui vemos el número de filas, columnas

(1474, 35)

In [65]:
df_talento.info() #aqui vemos el tipo de datos, los nulos, columnas, etc

<class 'pandas.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1401 non-null   float64
 1   Attrition                 1474 non-null   str
 2   BusinessTravel            1357 non-null   str
 3   DailyRate                 1474 non-null   int64
 4   Department                1445 non-null   str
 5   DistanceFromHome          1474 non-null   int64
 6   Education                 1474 non-null   int64
 7   EducationField            1416 non-null   str
 8   EmployeeCount             1474 non-null   int64
 9   EmployeeNumber            1474 non-null   int64
 10  EnvironmentSatisfaction   1474 non-null   int64
 11  Gender                    1474 non-null   str
 12  HourlyRate                1474 non-null   int64
 13  JobInvolvement            1474 non-null   int64
 14  JobLevel                  1474 non-null   int64
 15  JobRole                   1474 non-null   str
 16  JobSatisfaction           1445 non-null   float64
 17  MaritalStatus             1342 non-null   str
 18  MonthlyIncome             1460 non-null   float64
 19  MonthlyRate               1474 non-null   int64
 20  NumCompaniesWorked        1474 non-null   int64
 21  Over18                    1474 non-null   str
 22  OverTime                  1430 non-null   str
 23  PercentSalaryHike         1474 non-null   int64
 24  PerformanceRating         1474 non-null   int64
 25  RelationshipSatisfaction  1474 non-null   int64
 26  StandardHours             1310 non-null   float64
 27  StockOptionLevel          1474 non-null   int64
 28  TotalWorkingYears         1474 non-null   int64
 29  TrainingTimesLastYear     1386 non-null   float64
 30  WorkLifeBalance           1474 non-null   int64
 31  YearsAtCompany            1474 non-null   int64
 32  YearsInCurrentRole        1474 non-null   int64
 33  YearsSinceLastPromotion   1474 non-null   int64
 34  YearsWithCurrManager      1326 non-null   float64
dtypes: float64(6), int64(20), str(9)
memory usage: 403.2 KB

In [66]:
df_talento.duplicated().sum() #supuestamente hay 4 duplicados.

np.int64(4)

## columnas a modificar tras primera visualización

Age: float a int?

César:

- Attrition - Baja personal o rotación general
- DailyRate - Tarifa diaria, en código, dinero ??
- HourlyRate - Tarifa horaria, código o dinero ?? 
- JobLevel - Nivel de puesto ( jefe - intermedio - "peón")
-

In [67]:
df_talento[["MonthlyIncome", "MonthlyRate"]].sample(10)

      MonthlyIncome  MonthlyRate
1022         3500.0        25470
804         16885.0        16154
725          3743.0        10074
1426         2837.0        15919
268         13496.0         7501
1089         4285.0         3031
414          3202.0        21972
675          2329.0        11737
87           2075.0        18725
924          3506.0         6020

In [68]:
df_talento["ProfitMargen"] = (1 - df_talento["MonthlyIncome"] / df_talento["MonthlyRate"]) * 100

In [69]:
display(round(df_talento[["ProfitMargen", "MonthlyRate", "MonthlyIncome", "JobRole"]]), 2)

      ProfitMargen  MonthlyRate  MonthlyIncome                   JobRole
0             69.0        19479         5993.0          sALES eXECUTIVE
1             79.0        24907         5130.0       rESEARCH sCIENTIST
2             13.0         2396         2090.0    lABORATORY tECHNICIAN
3             87.0        23159         2909.0       rESEARCH sCIENTIST
4             79.0        16632         3468.0    lABORATORY tECHNICIAN
...            ...          ...            ...                       ...
1469          57.0        10228         4404.0    lABORATORY tECHNICIAN
1470          64.0        23490         8463.0          sALES eXECUTIVE
1471          83.0        26250         4450.0   mANUFACTURING dIRECTOR
1472          87.0        11585         1555.0          hUMAN rESOURCES
1473          48.0        18787         9724.0       rESEARCH sCIENTIST

[1474 rows x 4 columns]

2

In [70]:
df_talento["DailyRate"].sample(10)

820     1182
873      917
1029     663
866     1184
1208    1157
427     1499
1028    1283
458     1094
320     1377
66      1195
Name: DailyRate, dtype: int64

In [71]:
round(df_talento.isna().sum()/df_talento.shape[0] * 100), 2

(Age                          5.0
 Attrition                    0.0
 BusinessTravel               8.0
 DailyRate                    0.0
 Department                   2.0
 DistanceFromHome             0.0
 Education                    0.0
 EducationField               4.0
 EmployeeCount                0.0
 EmployeeNumber               0.0
 EnvironmentSatisfaction      0.0
 Gender                       0.0
 HourlyRate                   0.0
 JobInvolvement               0.0
 JobLevel                     0.0
 JobRole                      0.0
 JobSatisfaction              2.0
 MaritalStatus                9.0
 MonthlyIncome                1.0
 MonthlyRate                  0.0
 NumCompaniesWorked           0.0
 Over18                       0.0
 OverTime                     3.0
 PercentSalaryHike            0.0
 PerformanceRating            0.0
 RelationshipSatisfaction     0.0
 StandardHours               11.0
 StockOptionLevel             0.0
 TotalWorkingYears            0.0
 TrainingTimesLastYear        6.0
 WorkLifeBalance              0.0
 YearsAtCompany               0.0
 YearsInCurrentRole           0.0
 YearsSinceLastPromotion      0.0
 YearsWithCurrManager        10.0
 ProfitMargen                 1.0
 dtype: float64,
 2)

In [72]:
df_talento["Over18"].unique()

<StringArray>
['Y']
Length: 1, dtype: str

In [73]:
df_talento.sample()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,ProfitMargen
622,32.0,No,Travel_Rarely,117,Sales,13,4,Life Sciences,1,859,2,Male,73,3,2,sALES eXECUTIVE,4.0,Divorced,4403.0,9250,2,Y,No,11,3,3,80.0,1,8,3.0,2,5,2,0,3.0,52.4

In [74]:
df_talento["EmployeeCount"].unique()

array([1])

In [75]:
df_talento["JobSatisfaction"].isna().sum()

np.int64(29)

In [76]:
df_talento["Age"].isna().sum()

np.int64(73)

In [77]:
df_talento["Age"].dtype

dtype('float64')

In [78]:
display(df_talento.describe(include="str").T)

               count unique                     top  freq
Attrition       1474      2                      No  1236
BusinessTravel  1357      3           Travel_Rarely   955
Department      1445      3  Research & Development   941
EducationField  1416      6           Life Sciences   582
Gender          1474      2                    Male   885
JobRole         1474      9        sALES eXECUTIVE    327
MaritalStatus   1342      4                 Married   604
Over18          1474      1                       Y  1474
OverTime        1430      2                      No  1025

In [79]:
display(round(df_talento.describe(exclude=str).T), 2)

,count,mean,std,min,25%,50%,75%,max
Age,1401.0,37.0,9.0,18.0,30.0,36.0,43.0,60.0
DailyRate,1474.0,803.0,404.0,102.0,465.0,803.0,1157.0,1499.0
DistanceFromHome,1474.0,9.0,8.0,1.0,2.0,7.0,14.0,29.0
Education,1474.0,3.0,1.0,1.0,2.0,3.0,4.0,5.0
EmployeeCount,1474.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
EmployeeNumber,1474.0,1024.0,602.0,1.0,489.0,1020.0,1556.0,2068.0
EnvironmentSatisfaction,1474.0,3.0,1.0,1.0,2.0,3.0,4.0,4.0
HourlyRate,1474.0,66.0,20.0,30.0,48.0,66.0,84.0,100.0
JobInvolvement,1474.0,3.0,1.0,1.0,2.0,3.0,3.0,4.0
JobLevel,1474.0,2.0,1.0,1.0,1.0,2.0,3.0,5.0
JobSatisfaction,1445.0,3.0,1.0,1.0,2.0,3.0,4.0,4.0
MonthlyIncome,1460.0,6497.0,4706.0,1009.0,2909.0,4907.0,8377.0,19999.0
MonthlyRate,1474.0,14329.0,7120.0,2094.0,8054.0,14248.0,20466.0,26999.0
NumCompaniesWorked,1474.0,3.0,2.0,0.0,1.0,2.0,4.0,9.0
PercentSalaryHike,1474.0,15.0,4.0,11.0,12.0,14.0,18.0,25.0
PerformanceRating,1474.0,3.0,0.0,3.0,3.0,3.0,3.0,4.0
RelationshipSatisfaction,1474.0,3.0,1.0,1.0,2.0,3.0,4.0,4.0
StandardHours,1310.0,80.0,0.0,80.0,80.0,80.0,80.0,80.0
StockOptionLevel,1474.0,1.0,1.0,0.0,0.0,1.0,1.0,3.0
TotalWorkingYears,1474.0,11.0,8.0,0.0,6.0,10.0,15.0,40.0
TrainingTimesLastYear,1386.0,3.0,1.0,0.0,2.0,3.0,3.0,6.0
WorkLifeBalance,1474.0,3.0,1.0,1.0,2.0,3.0,3.0,4.0
YearsAtCompany,1474.0,7.0,6.0,0.0,3.0,5.0,9.0,40.0
YearsInCurrentRole,1474.0,4.0,4.0,0.0,2.0,3.0,7.0,18.0
YearsSinceLastPromotion,1474.0,2.0,3.0,0.0,0.0,1.0,3.0,15.0
YearsWithCurrManager,1326.0,4.0,4.0,0.0,2.0,3.0,7.0,17.0
ProfitMargen,1460.0,33.0,84.0,-818.0,23.0,60.0,78.0,96.0

2

In [80]:
df_talento["JobRole"] = df_talento["JobRole"].str.lower()

In [81]:
df_talento["JobRole"]

0               sales executive
1            research scientist
2         laboratory technician
3            research scientist
4         laboratory technician
                  ...
1469      laboratory technician
1470            sales executive
1471     manufacturing director
1472            human resources
1473         research scientist
Name: JobRole, Length: 1474, dtype: str

In [82]:
df_talento.duplicated().sum()

np.int64(4)

In [83]:
df_talento["JobRole"].str.strip().str.capitalize()

0              Sales executive
1           Research scientist
2        Laboratory technician
3           Research scientist
4        Laboratory technician
                 ...
1469     Laboratory technician
1470           Sales executive
1471    Manufacturing director
1472           Human resources
1473        Research scientist
Name: JobRole, Length: 1474, dtype: str